development:
  host: localhost
  database: ubimachine_development

test:
  host: localhost
  database: ubimachine_test

# set these environment variables on your prod server
production:
    uri: 'mongodb://heroku_new:getr1ch0rd1etry1nm0f0@now-production.m0.mongolayer.com:27017/now_production'
    persist_in_safe_mode: true 
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
  #mongodb://heroku:c02c2c3a696b0785f962754467945eed@pearl.mongohq.com:27029/ubimachine
