development:
  host: localhost
  database: ubimachine_development

test:
  host: localhost
  database: ubimachine_test

# set these environment variables on your prod server
production:
    uri: 'mongodb://heroku:c02c2c3a696b0785f962754467945eed@pearl.mongohq.com:27029/ubimachine'
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
