fetch_photos_newyork:
  every: "30s"
  class: Fetchigphotos
  args: "976138"
  description: "Fetchs instagram pics every minute"
  
fetch_photos_paris:
  every: "30s"
  class: Fetchigphotos
  args: "976141"
  description: "Fetchs instagram pics every minute"
  
# fetch_photos_tokyo:
#   every: "2m"
#   class: Fetchigphotos
#   args: "772800"
#   description: "Fetchs instagram pics every minute"
  
fetch_photos_london:
  every: "30s"
  class: Fetchigphotos
  args: "976145"
  description: "Fetchs instagram pics every minute"
  
fetch_photos_sanfrancisco:
  every: "30s"
  class: Fetchigphotos
  args: "976142"
  description: "Fetchs instagram pics every minute"
  
trending:
  every: "10m"
  class: Trending
  args: "1"
  description: "Trending emails"