fetch_photos_newyork1:
  every: "30s"
  class: Fetchigphotos
  args: "1325674"
  description: "Fetchs instagram pics every minute"

fetch_photos_newyork2:
  every: "30s"
  class: Fetchigphotos
  args: "1325676"
  description: "Fetchs instagram pics every minute"

fetch_photos_sanfrancisco1:
  every: "30s"
  class: Fetchigphotos
  args: "1325678"
  description: "Fetchs instagram pics every minute"

fetch_photos_sanfrancisco2:
  every: "30s"
  class: Fetchigphotos
  args: "1325682"
  description: "Fetchs instagram pics every minute"

fetch_photos_paris1:
  every: "30s"
  class: Fetchigphotos
  args: "1325683"
  description: "Fetchs instagram pics every minute"

fetch_photos_paris2:
  every: "30s"
  class: Fetchigphotos
  args: "1325686"
  description: "Fetchs instagram pics every minute"

fetch_photos_losangeles1:
  every: "30s"
  class: Fetchigphotos
  args: "1325694"
  description: "Fetchs instagram pics every minute"

fetch_photos_losangeles2:
  every: "30s"
  class: Fetchigphotos
  args: "1325696"
  description: "Fetchs instagram pics every minute"

fetch_photos_losangeles3:
  every: "30s"
  class: Fetchigphotos
  args: "1325704"
  description: "Fetchs instagram pics every minute"

fetch_photos_london:
  every: "30s"
  class: Fetchigphotos
  args: "1325687"
  description: "Fetchs instagram pics every minute"

trending:
  every: "10m"
  class: Trending
  args: "2"
  description: "Trending emails"