fetch_photos_every_minute:
  cron: "60 * * * * *"
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1min
  class: Fetchigphotos
  args: 
  description: "Fetchs instagram pics every minute"