fetch_venue_new:
  every: "15m"
  class: Trending3
  args: 
  description: "New Photo Fetch and Trending" 

maintenance:
  every: "10m"
  class: Maintenance
  args: 
  description: "remove duplicate events and photos"

people_trending:
  every: "1m"
  class: TrendingPeople
  args: 
  description: "updating events created by members of Now community"

auto_ig_events:
  every: "1m"
  class: UserFollowEvent2
  args: 
  description: "pull recent instagram photos from our tastemakers -- create an event if its good"
