fetch_photos_newyork:
  every: "2m"
  class: Fetchigphotos
  args: "823413"
  description: "Fetchs instagram pics every minute"
  
fetch_photos_paris:
  every: "2m"
  class: Fetchigphotos
  args: "823414"
  description: "Fetchs instagram pics every minute"
  
# fetch_photos_tokyo:
#   every: "2m"
#   class: Fetchigphotos
#   args: "772800"
#   description: "Fetchs instagram pics every minute"
  
fetch_photos_london:
  every: "2m"
  class: Fetchigphotos
  args: "823416"
  description: "Fetchs instagram pics every minute"
  
fetch_photos_sanfrancisco:
  every: "2m"
  class: Fetchigphotos
  args: "823415"
  description: "Fetchs instagram pics every minute"
  
fetch_photos_austin:
  every: "2m"
  class: Fetchigphotos
  args: "914326"
  description: "Fetchs instagram pics every minute"