fetch_photos_newyork:
  every: "1m"
  class: Fetchigphotos
  args: "702469"
  description: "Fetchs instagram pics every minute"
  
fetch_photos_newyork:
  every: "1m"
  class: Fetchigphotos
  args: "756596"
  description: "Fetchs instagram pics every minute"