fetch_photos_newyork1:
  every: "30s"
  class: Fetchigphotos
  args: "1325529"
  description: "Fetchs instagram pics every minute"

fetch_photos_newyork2:
  every: "30s"
  class: Fetchigphotos
  args: "1325530"
  description: "Fetchs instagram pics every minute"

fetch_photos_sanfrancisco1:
  every: "30s"
  class: Fetchigphotos
  args: "1325531"
  description: "Fetchs instagram pics every minute"

fetch_photos_sanfrancisco2:
  every: "30s"
  class: Fetchigphotos
  args: "1325534"
  description: "Fetchs instagram pics every minute"

fetch_photos_paris1:
  every: "30s"
  class: Fetchigphotos
  args: "1325535"
  description: "Fetchs instagram pics every minute"

fetch_photos_paris2:
  every: "30s"
  class: Fetchigphotos
  args: "1325536"
  description: "Fetchs instagram pics every minute"

fetch_photos_losangeles1:
  every: "30s"
  class: Fetchigphotos
  args: "1325545"
  description: "Fetchs instagram pics every minute"

fetch_photos_losangeles2:
  every: "30s"
  class: Fetchigphotos
  args: "1325547"
  description: "Fetchs instagram pics every minute"

fetch_photos_losangeles3:
  every: "30s"
  class: Fetchigphotos
  args: "1325550"
  description: "Fetchs instagram pics every minute"

fetch_photos_london:
  every: "30s"
  class: Fetchigphotos
  args: "1325542"
  description: "Fetchs instagram pics every minute"

trending:
  every: "10m"
  class: Trending
  args: "2"
  description: "Trending emails"