fetch_photos_every_minute:
  every: "1m"
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1min
  class: Fetchigphotos
  args: 
  description: "Fetchs instagram pics every minute"
  
Do_all_feed:
  every: "2m"
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1min
  class: Categoryfeeds
  args: "all"
  description: "create feed for all"

Do_food_feed:
  every: "2m"
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1min
  class: Categoryfeeds
  args: "Food"
  description: "create feed for food"

Do_nightlife_feed:
  every: "2m"
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1min
  class: Categoryfeeds
  args: "Nightlife Spot"
  description: "create feed for nightlife"
  
Do_arts_feed:
  every: "2m"
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1min
  class: Categoryfeeds
  args: "Arts & Entertainment"
  description: "create feed for arts"
  
Do_outdoors_feed:
  every: "2m"
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1min
  class: Categoryfeeds
  args: "Great Outdoors"
  description: "create feed for outdoors"
