fetch_photos_newyork:
  every: "2m"
  class: Fetchigphotos
  args: "785118"
  description: "Fetchs instagram pics every minute"
  
fetch_photos_paris:
  every: "2m"
  class: Fetchigphotos
  args: "785120"
  description: "Fetchs instagram pics every minute"
  
# fetch_photos_tokyo:
#   every: "2m"
#   class: Fetchigphotos
#   args: "772800"
#   description: "Fetchs instagram pics every minute"
  
fetch_photos_london:
  every: "2m"
  class: Fetchigphotos
  args: "785122"
  description: "Fetchs instagram pics every minute"
  
fetch_photos_sanfrancisco:
  every: "2m"
  class: Fetchigphotos
  args: "785121"
  description: "Fetchs instagram pics every minute"
  
  