fetch_photos_newyork:
  every: "1m"
  class: Fetchigphotos
  args: "772798"
  description: "Fetchs instagram pics every minute"
  
fetch_photos_paris:
  every: "1m"
  class: Fetchigphotos
  args: "772799"
  description: "Fetchs instagram pics every minute"
  
fetch_photos_tokyo:
  every: "1m"
  class: Fetchigphotos
  args: "772800"
  description: "Fetchs instagram pics every minute"
  
fetch_photos_london:
  every: "1m"
  class: Fetchigphotos
  args: "772804"
  description: "Fetchs instagram pics every minute"
  
fetch_photos_sanfrancisco:
  every: "1m"
  class: Fetchigphotos
  args: "772803"
  description: "Fetchs instagram pics every minute"
  
  