#fetch_venue_new:
#  every: "15m"
#  class: Trending3
#  args: 
#  description: "New Photo Fetch and Trending" 

maintenance:
  every: "10m"
  class: Maintenance
  args: 
  description: "remove duplicate events and photos"

people_trending:
  every: "1m"
  class: TrendingPeople
  args: 
  description: "updating events created by members of Now community"

auto_ig_events:
  every: "30s"
  class: UserFollowEvent2
  args: 
  description: "pull recent instagram photos from our tastemakers -- create an event if its good"

drain_event_opens:
  every: "5m"
  class: DrainAnalytics
  args: 
  description: "Enter recent activity into the database"

city_rank:
  every: "10m"
  class: CityRank
  args:
  description: "Count the events in cities"

reengagement:
  every: "15m"
  class: Reengagement
  args:
  description: "Send Reengagement Pushes"

verify_drain:
  every: "1m"
  class: VerifyQueueDrain
  args:
  description: "Clean bad photos in events that are getting lots of views"

update_city_cache:
  every: "10m"
  class: CacheCityEvents
  args:
  description: "Cache events in city search for faster access"

user_follow3:
  every: "1m"
  class: UserFollow3
  args: 
  description: "Pull venue watches from user feeds"

venue_watch:
  every: "20s"
  class: WatchVenue
  args:
  description: "examine venues we're watching"
