fetch_photos_newyork1:
  every: "25s"
  class: Fetchigphotos
  args: "1327809"
  description: "Fetchs instagram pics every minute"

fetch_photos_newyork2:
  every: "25s"
  class: Fetchigphotos
  args: "1327810"
  description: "Fetchs instagram pics every minute"

fetch_photos_sanfrancisco1:
  every: "35s"
  class: Fetchigphotos
  args: "1327811"
  description: "Fetchs instagram pics every minute"

fetch_photos_sanfrancisco2:
  every: "35s"
  class: Fetchigphotos
  args: "1327814"
  description: "Fetchs instagram pics every minute"

fetch_photos_paris1:
  every: "45s"
  class: Fetchigphotos
  args: "1327815"
  description: "Fetchs instagram pics every minute"

fetch_photos_paris2:
  every: "45s"
  class: Fetchigphotos
  args: "1327816"
  description: "Fetchs instagram pics every minute"

fetch_photos_losangeles1:
  every: "25s"
  class: Fetchigphotos
  args: "1327818"
  description: "Fetchs instagram pics every minute"

fetch_photos_losangeles2:
  every: "25s"
  class: Fetchigphotos
  args: "1327819"
  description: "Fetchs instagram pics every minute"

fetch_photos_losangeles3:
  every: "25s"
  class: Fetchigphotos
  args: "1327821"
  description: "Fetchs instagram pics every minute"

fetch_photos_london:
  every: "40s"
  class: Fetchigphotos
  args: "1327817"
  description: "Fetchs instagram pics every minute"

trending:
  every: "10m"
  class: Trending
  args: "2"
  description: "Trending emails"